// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    [Migration("20260819200155_AddRestrictDeleteBehaviorPersonToPartner")]
    partial class AddRestrictDeleteBehaviorPersonToPartner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("844ef091-c288-47f4-8edb-884cee07aaa6"),
                            AnnualSalary = 3000m,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("31221fda-95c9-4da7-a168-250d41d3257a")
                        },
                        new
                        {
                            Id = new Guid("3511646d-8567-46ad-9d05-74a2fac21f91"),
                            AnnualSalary = 4000m,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("31221fda-95c9-4da7-a168-250d41d3257a")
                        },
                        new
                        {
                            Id = new Guid("9a201367-19cb-4cd7-a7e7-e20a1d7c1562"),
                            AnnualSalary = 2000m,
                            Title = "Teacher",
                            WorkplaceId = new Guid("17ebdb58-0989-4061-b66c-78173ebeac5a")
                        },
                        new
                        {
                            Id = new Guid("b5631cc9-d4f2-4014-8f50-5c6f4d6cfe2f"),
                            AnnualSalary = 4500m,
                            Title = "Doctor",
                            WorkplaceId = new Guid("abeb2d35-c30b-40b1-8e5c-abacf8f6f437")
                        },
                        new
                        {
                            Id = new Guid("caf684c8-f8b3-42b9-83a1-ce99c66b6c06"),
                            AnnualSalary = 2500m,
                            Title = "Nurse",
                            WorkplaceId = new Guid("abeb2d35-c30b-40b1-8e5c-abacf8f6f437")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.HasIndex("PartnerId")
                        .IsUnique()
                        .HasFilter("[PartnerId] IS NOT NULL");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b1cdd4f-6e73-48f5-95db-a847e25234b5"),
                            Age = 22,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 0,
                            JobId = new Guid("844ef091-c288-47f4-8edb-884cee07aaa6"),
                            Money = 0m,
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("6ca886ca-0033-434d-893b-1fd7d8272769"),
                            Age = 28,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 1,
                            JobId = new Guid("9a201367-19cb-4cd7-a7e7-e20a1d7c1562"),
                            Money = 0m,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("697cb4d9-6530-43d6-a0c3-a0d2ca7c3ebe"),
                            Age = 35,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 0,
                            JobId = new Guid("3511646d-8567-46ad-9d05-74a2fac21f91"),
                            Money = 0m,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("cd4e25e2-c376-42f2-bfd1-679e19d9a55a"),
                            Age = 31,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 1,
                            JobId = new Guid("b5631cc9-d4f2-4014-8f50-5c6f4d6cfe2f"),
                            Money = 0m,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("ff5c4db5-d6cb-4c79-a723-c9546edfdf4b"),
                            Age = 25,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 0,
                            JobId = new Guid("caf684c8-f8b3-42b9-83a1-ce99c66b6c06"),
                            Money = 0m,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("94adffcc-fb7a-4f93-880f-0b8e14669f6a"),
                            Age = 17,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("8ff3cba4-bab9-41c2-b990-a50fe59a4fc3"),
                            Age = 16,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 0,
                            Money = 0m,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("4e1fa8ad-4819-49ef-bf64-0d20520f2d7e"),
                            Age = 8,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("fda5dee7-e66d-45c6-bd45-d9756d0018e2"),
                            Age = 67,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 0,
                            Money = 0m,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("1f1a6935-51ef-4368-adb5-cd99df124867"),
                            Age = 70,
                            CityId = new Guid("f6a87de8-abd7-4bd0-a69c-ea5735e8a10e"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31221fda-95c9-4da7-a168-250d41d3257a"),
                            Capacity = 10,
                            Name = "Tech Company"
                        },
                        new
                        {
                            Id = new Guid("17ebdb58-0989-4061-b66c-78173ebeac5a"),
                            Capacity = 5,
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("abeb2d35-c30b-40b1-8e5c-abacf8f6f437"),
                            Capacity = 5,
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CitySimulation.Domain.Entities.Person", "Partner")
                        .WithOne()
                        .HasForeignKey("CitySimulation.Domain.Entities.Person", "PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Job");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
