// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    [Migration("20260819195805_AddMoneyPropToPersonAndEditSalaryToAnnulSalaryInJob")]
    partial class AddMoneyPropToPersonAndEditSalaryToAnnulSalaryInJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16e1b967-3326-4ca8-801e-15828447f2ac"),
                            AnnualSalary = 3000m,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("7e76b8eb-ac42-436e-9045-153286f5a333")
                        },
                        new
                        {
                            Id = new Guid("328cb786-10de-4b72-9bcc-b30d502df34a"),
                            AnnualSalary = 4000m,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("7e76b8eb-ac42-436e-9045-153286f5a333")
                        },
                        new
                        {
                            Id = new Guid("6551d8ac-f741-4a40-b776-c36070d4c7eb"),
                            AnnualSalary = 2000m,
                            Title = "Teacher",
                            WorkplaceId = new Guid("508d59e5-41b6-4560-bf9d-8b11ecde274d")
                        },
                        new
                        {
                            Id = new Guid("4a7dc922-2408-4885-be9e-dbc1c8d86e46"),
                            AnnualSalary = 4500m,
                            Title = "Doctor",
                            WorkplaceId = new Guid("f94949b1-b1ba-452b-813b-a78202f4e875")
                        },
                        new
                        {
                            Id = new Guid("438cd5dd-a5c2-453b-8de5-8ddea426ccf9"),
                            AnnualSalary = 2500m,
                            Title = "Nurse",
                            WorkplaceId = new Guid("f94949b1-b1ba-452b-813b-a78202f4e875")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84bd3808-fb5b-4865-a118-52410f6d7002"),
                            Age = 22,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 0,
                            JobId = new Guid("16e1b967-3326-4ca8-801e-15828447f2ac"),
                            Money = 0m,
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("418255a0-8646-419d-836a-028229a0515c"),
                            Age = 28,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 1,
                            JobId = new Guid("6551d8ac-f741-4a40-b776-c36070d4c7eb"),
                            Money = 0m,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("c3a2a8f4-dbd7-4d62-89ea-ba81ba825e11"),
                            Age = 35,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 0,
                            JobId = new Guid("328cb786-10de-4b72-9bcc-b30d502df34a"),
                            Money = 0m,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("61462904-0af5-429f-98be-2756187952a5"),
                            Age = 31,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 1,
                            JobId = new Guid("4a7dc922-2408-4885-be9e-dbc1c8d86e46"),
                            Money = 0m,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("e413fb20-b525-4abb-a61c-3f06459396ef"),
                            Age = 25,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 0,
                            JobId = new Guid("438cd5dd-a5c2-453b-8de5-8ddea426ccf9"),
                            Money = 0m,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("9be88d60-ea11-48cb-8002-fde5c3b28407"),
                            Age = 17,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("a8f9a481-f34d-4b72-a3a5-686b29c69c57"),
                            Age = 16,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 0,
                            Money = 0m,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("d693dd51-0eb0-4e9b-a937-453631f977ca"),
                            Age = 8,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("a0775f49-8734-4bfa-be5e-eae51e6373c2"),
                            Age = 67,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 0,
                            Money = 0m,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("68e84d67-649b-4d0b-88eb-0c4c53963b93"),
                            Age = 70,
                            CityId = new Guid("a8bd7ba3-63bd-4874-a617-e41d80868960"),
                            Gender = 1,
                            Money = 0m,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e76b8eb-ac42-436e-9045-153286f5a333"),
                            Capacity = 10,
                            Name = "Tech Company"
                        },
                        new
                        {
                            Id = new Guid("508d59e5-41b6-4560-bf9d-8b11ecde274d"),
                            Capacity = 5,
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("f94949b1-b1ba-452b-813b-a78202f4e875"),
                            Capacity = 5,
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CitySimulation.Domain.Entities.Person", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("City");

                    b.Navigation("Job");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
