// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    [Migration("20260819203202_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d15b85a-21c6-4dc5-abef-87f3210b9575"),
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Money = 100000m,
                            Name = "LvivTech"
                        },
                        new
                        {
                            Id = new Guid("f3059cf6-850d-4b4f-a6be-bd848cf37c9a"),
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Money = 50000m,
                            Name = "Lviv Education"
                        },
                        new
                        {
                            Id = new Guid("9201172d-f027-47a7-9a4a-01a6054c9c78"),
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Money = 150000m,
                            Name = "Lviv Health"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa0312dc-932b-4b6b-82d3-36e60b40f847"),
                            AnnualSalary = 3000m,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("f35827e8-1e4b-4fde-8d0f-c13b19efbca0")
                        },
                        new
                        {
                            Id = new Guid("3b3f07bc-16ee-4aea-907c-3d4488de4602"),
                            AnnualSalary = 4000m,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("f35827e8-1e4b-4fde-8d0f-c13b19efbca0")
                        },
                        new
                        {
                            Id = new Guid("034ddd96-db4a-473a-9e6c-0af9b9667d73"),
                            AnnualSalary = 2000m,
                            Title = "Teacher",
                            WorkplaceId = new Guid("d2b917be-1d6a-4573-9c15-a4cf31cb139a")
                        },
                        new
                        {
                            Id = new Guid("76415459-d820-4645-bd72-1ab96d7e92a9"),
                            AnnualSalary = 4500m,
                            Title = "Doctor",
                            WorkplaceId = new Guid("95c4785c-6925-4498-88c3-764f5d75d2de")
                        },
                        new
                        {
                            Id = new Guid("2a8bc2f4-6362-4a5f-81cc-5306d396e524"),
                            AnnualSalary = 2500m,
                            Title = "Nurse",
                            WorkplaceId = new Guid("95c4785c-6925-4498-88c3-764f5d75d2de")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LivingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.HasIndex("PartnerId")
                        .IsUnique()
                        .HasFilter("[PartnerId] IS NOT NULL");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5af65687-7427-41d3-ab7c-43b6a0772b7a"),
                            Age = 22,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 0,
                            JobId = new Guid("fa0312dc-932b-4b6b-82d3-36e60b40f847"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("8cbc58aa-aa1c-41d7-98e3-0fb7db93d84d"),
                            Age = 28,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 1,
                            JobId = new Guid("034ddd96-db4a-473a-9e6c-0af9b9667d73"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("af506742-37ef-42d6-8198-fb0099d80365"),
                            Age = 35,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 0,
                            JobId = new Guid("3b3f07bc-16ee-4aea-907c-3d4488de4602"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("f89d8f19-977b-45a8-a0e9-eac070d6ec41"),
                            Age = 31,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 1,
                            JobId = new Guid("76415459-d820-4645-bd72-1ab96d7e92a9"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("f9fdba5a-4baf-4b39-a0bb-7ead1e693074"),
                            Age = 25,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 0,
                            JobId = new Guid("2a8bc2f4-6362-4a5f-81cc-5306d396e524"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("83a6afa1-a8c6-4c22-9e60-d304724e41e7"),
                            Age = 17,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("2dcebe48-649f-479e-a859-22336076ce48"),
                            Age = 16,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 0,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("f1e0f11d-541b-41d3-9191-738bf9bd4cba"),
                            Age = 8,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("cdcb284a-c636-449e-a3ee-3f0987c28586"),
                            Age = 67,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 0,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("49f5aadb-6e4b-4758-93d3-0f646c6a810e"),
                            Age = 70,
                            CityId = new Guid("71e68882-246a-4585-8c93-5e09b953f288"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f35827e8-1e4b-4fde-8d0f-c13b19efbca0"),
                            Capacity = 10,
                            CompanyId = new Guid("5d15b85a-21c6-4dc5-abef-87f3210b9575"),
                            Name = "Tech Office"
                        },
                        new
                        {
                            Id = new Guid("d2b917be-1d6a-4573-9c15-a4cf31cb139a"),
                            Capacity = 5,
                            CompanyId = new Guid("f3059cf6-850d-4b4f-a6be-bd848cf37c9a"),
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("95c4785c-6925-4498-88c3-764f5d75d2de"),
                            Capacity = 5,
                            CompanyId = new Guid("9201172d-f027-47a7-9a4a-01a6054c9c78"),
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Company", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany("Jobs")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CitySimulation.Domain.Entities.Person", "Partner")
                        .WithOne()
                        .HasForeignKey("CitySimulation.Domain.Entities.Person", "PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Job");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Company", "Company")
                        .WithMany("Workplaces")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Company", b =>
                {
                    b.Navigation("Workplaces");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
