// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    [Migration("20260818190521_AddPatnerToPersonEntity")]
    partial class AddPatnerToPersonEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b1ce234-f0fe-4138-9123-bf214bf5555b"),
                            Salary = 3000,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("0fe42522-4d18-4251-a0ef-f7d3e98b20cf")
                        },
                        new
                        {
                            Id = new Guid("acbc6165-c0dc-4af7-a33f-4e5dfe24b2d7"),
                            Salary = 4000,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("0fe42522-4d18-4251-a0ef-f7d3e98b20cf")
                        },
                        new
                        {
                            Id = new Guid("ab707990-22be-4a3d-a964-82638fd719ab"),
                            Salary = 2000,
                            Title = "Teacher",
                            WorkplaceId = new Guid("b13a6e29-0933-4daf-bb52-482924f29f38")
                        },
                        new
                        {
                            Id = new Guid("25a20379-7696-47fa-a685-a702fb20858f"),
                            Salary = 4500,
                            Title = "Doctor",
                            WorkplaceId = new Guid("5da77971-c022-44d2-8169-fcc0f12d9383")
                        },
                        new
                        {
                            Id = new Guid("d7bbe413-829d-42db-b68b-094a07793849"),
                            Salary = 2500,
                            Title = "Nurse",
                            WorkplaceId = new Guid("5da77971-c022-44d2-8169-fcc0f12d9383")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.HasIndex("PartnerId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8349f334-0f7e-4d4e-9bf6-9a610e622bdb"),
                            Age = 22,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 0,
                            JobId = new Guid("0b1ce234-f0fe-4138-9123-bf214bf5555b"),
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("6995627f-51dd-4772-a041-91e28def0cdd"),
                            Age = 28,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 1,
                            JobId = new Guid("ab707990-22be-4a3d-a964-82638fd719ab"),
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("38e9cf12-aebc-4f37-9f58-4d009b067e82"),
                            Age = 35,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 0,
                            JobId = new Guid("acbc6165-c0dc-4af7-a33f-4e5dfe24b2d7"),
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("f968793c-dd27-4ded-b2b1-bd62f070f373"),
                            Age = 31,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 1,
                            JobId = new Guid("25a20379-7696-47fa-a685-a702fb20858f"),
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("c21098ce-5f32-49ed-9363-d596d95d3f25"),
                            Age = 25,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 0,
                            JobId = new Guid("d7bbe413-829d-42db-b68b-094a07793849"),
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("1215714b-4e11-4f64-bc69-6874d039974c"),
                            Age = 17,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 1,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("73aa66b6-12ce-4901-87e7-eb8bbe187ffa"),
                            Age = 16,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 0,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("78f9b7d2-67ee-44dc-89d9-4117b7ce10c7"),
                            Age = 8,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 1,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("e866e4e4-7a84-4c4e-ba3b-6beb1abd422c"),
                            Age = 67,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 0,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("71aec48b-620c-4db7-918a-4210dd2a058a"),
                            Age = 70,
                            CityId = new Guid("0671f1db-4475-426e-8652-b698be601684"),
                            Gender = 1,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fe42522-4d18-4251-a0ef-f7d3e98b20cf"),
                            Capacity = 10,
                            Name = "Tech Company"
                        },
                        new
                        {
                            Id = new Guid("b13a6e29-0933-4daf-bb52-482924f29f38"),
                            Capacity = 5,
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("5da77971-c022-44d2-8169-fcc0f12d9383"),
                            Capacity = 5,
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CitySimulation.Domain.Entities.Person", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId");

                    b.Navigation("City");

                    b.Navigation("Job");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
