// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    [Migration("20260819200644_AddLivingCostToPErson")]
    partial class AddLivingCostToPErson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7aa3fe04-cc0d-4a71-bf1e-c2056c148899"),
                            AnnualSalary = 3000m,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("1e973114-3f0b-4a68-a1cb-6351d5c58e19")
                        },
                        new
                        {
                            Id = new Guid("31e161a7-233c-4c07-a793-e8855d66abd0"),
                            AnnualSalary = 4000m,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("1e973114-3f0b-4a68-a1cb-6351d5c58e19")
                        },
                        new
                        {
                            Id = new Guid("483d36b6-0f37-434e-ba7e-8cd419489611"),
                            AnnualSalary = 2000m,
                            Title = "Teacher",
                            WorkplaceId = new Guid("4e5adcce-cb0b-4d2a-92ae-03802011bbb7")
                        },
                        new
                        {
                            Id = new Guid("90e78a65-b781-4a81-8a81-efce26a4b90d"),
                            AnnualSalary = 4500m,
                            Title = "Doctor",
                            WorkplaceId = new Guid("c168f849-9964-4e83-a610-c2a19f8d8821")
                        },
                        new
                        {
                            Id = new Guid("0182d978-7424-43aa-8516-07f72c96abc3"),
                            AnnualSalary = 2500m,
                            Title = "Nurse",
                            WorkplaceId = new Guid("c168f849-9964-4e83-a610-c2a19f8d8821")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LivingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.HasIndex("PartnerId")
                        .IsUnique()
                        .HasFilter("[PartnerId] IS NOT NULL");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fc54110-eb46-40c3-a9a5-f86a991bbb79"),
                            Age = 22,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 0,
                            JobId = new Guid("7aa3fe04-cc0d-4a71-bf1e-c2056c148899"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("e545f057-3801-4190-a984-703a5aa8909c"),
                            Age = 28,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 1,
                            JobId = new Guid("483d36b6-0f37-434e-ba7e-8cd419489611"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("dcaf5951-377a-4106-a9cd-a20fb046ccd8"),
                            Age = 35,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 0,
                            JobId = new Guid("31e161a7-233c-4c07-a793-e8855d66abd0"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("fc975e4e-dd7d-40ed-bd52-41142e7eb22b"),
                            Age = 31,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 1,
                            JobId = new Guid("90e78a65-b781-4a81-8a81-efce26a4b90d"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("af6481e8-80a0-47bd-bcbc-2c2c926523ba"),
                            Age = 25,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 0,
                            JobId = new Guid("0182d978-7424-43aa-8516-07f72c96abc3"),
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("5828f5ad-223f-4a5e-8a93-fe4bd5f62619"),
                            Age = 17,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("6f91a300-b8f6-46a0-b9fd-d7b6299a5d68"),
                            Age = 16,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 0,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("aa9c490a-b3c4-4203-a795-9c79debef739"),
                            Age = 8,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("19b33a99-037c-44b4-852a-7fda0ebbcae0"),
                            Age = 67,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 0,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("96618793-8305-4aba-8c36-883e7dd74c6b"),
                            Age = 70,
                            CityId = new Guid("59b8a68f-913a-4a06-a532-0da494c71099"),
                            Gender = 1,
                            LivingCost = 0m,
                            Money = 0m,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e973114-3f0b-4a68-a1cb-6351d5c58e19"),
                            Capacity = 10,
                            Name = "Tech Company"
                        },
                        new
                        {
                            Id = new Guid("4e5adcce-cb0b-4d2a-92ae-03802011bbb7"),
                            Capacity = 5,
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("c168f849-9964-4e83-a610-c2a19f8d8821"),
                            Capacity = 5,
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CitySimulation.Domain.Entities.Person", "Partner")
                        .WithOne()
                        .HasForeignKey("CitySimulation.Domain.Entities.Person", "PartnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Job");

                    b.Navigation("Partner");
                });
#pragma warning restore 612, 618
        }
    }
}
