// <auto-generated />
using System;
using CitySimulation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitySimulation.Persistence.Migrations
{
    [DbContext(typeof(CitySimulationDbContext))]
    partial class CitySimulationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitySimulation.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Name = "Lviv"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a56ce67-81d7-4aec-b63d-0aa660a35241"),
                            Salary = 3000,
                            Title = "Software Developer",
                            WorkplaceId = new Guid("90661f93-d29b-4282-b43f-a5c2b1ae120b")
                        },
                        new
                        {
                            Id = new Guid("1a87ee13-a494-4e33-8098-82f6552cb167"),
                            Salary = 4000,
                            Title = "Project Manager",
                            WorkplaceId = new Guid("90661f93-d29b-4282-b43f-a5c2b1ae120b")
                        },
                        new
                        {
                            Id = new Guid("8165c34b-de0a-4219-b4ca-ce4bd666be66"),
                            Salary = 2000,
                            Title = "Teacher",
                            WorkplaceId = new Guid("ddc380f3-7ae8-4766-b147-aba16bc259da")
                        },
                        new
                        {
                            Id = new Guid("0d3d2c4b-839b-45a9-b1ba-5e4f1e51c773"),
                            Salary = 4500,
                            Title = "Doctor",
                            WorkplaceId = new Guid("208fb852-49a2-4e83-a380-cd0c364fbd65")
                        },
                        new
                        {
                            Id = new Guid("66cb4162-e423-4779-a48a-28c1b0a49b49"),
                            Salary = 2500,
                            Title = "Nurse",
                            WorkplaceId = new Guid("208fb852-49a2-4e83-a380-cd0c364fbd65")
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("JobId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("117f4d96-d91c-4822-8107-d38109fec3e4"),
                            Age = 22,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 0,
                            JobId = new Guid("3a56ce67-81d7-4aec-b63d-0aa660a35241"),
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("29408384-5154-46cd-845b-68596e35984e"),
                            Age = 28,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 1,
                            JobId = new Guid("8165c34b-de0a-4219-b4ca-ce4bd666be66"),
                            Name = "Anna"
                        },
                        new
                        {
                            Id = new Guid("9dacc560-a3e1-4516-8e34-cc49b657ffc5"),
                            Age = 35,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 0,
                            JobId = new Guid("1a87ee13-a494-4e33-8098-82f6552cb167"),
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("656d0a00-ef8e-4b05-880d-6ef73daee850"),
                            Age = 31,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 1,
                            JobId = new Guid("0d3d2c4b-839b-45a9-b1ba-5e4f1e51c773"),
                            Name = "Emma"
                        },
                        new
                        {
                            Id = new Guid("5cf2777b-e8ab-434b-83a7-9f9de7066ca1"),
                            Age = 25,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 0,
                            JobId = new Guid("66cb4162-e423-4779-a48a-28c1b0a49b49"),
                            Name = "Alex"
                        },
                        new
                        {
                            Id = new Guid("cfa3e603-cec9-4c06-9b83-cbe80aeab478"),
                            Age = 17,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 1,
                            Name = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("2d2856ac-e397-4bbf-830e-936ea8a4b092"),
                            Age = 16,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 0,
                            Name = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("4424ac4a-e973-4230-a7f1-ad3cccbb84ef"),
                            Age = 8,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 1,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = new Guid("70eab2fa-ced4-4fe2-aedf-526e6ee271e8"),
                            Age = 67,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 0,
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("86460eee-5fdf-4caa-be6c-36b6454a2c15"),
                            Age = 70,
                            CityId = new Guid("fc911511-5645-420c-b821-49ea5df976e8"),
                            Gender = 1,
                            Name = "Mia"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90661f93-d29b-4282-b43f-a5c2b1ae120b"),
                            Capacity = 10,
                            Name = "Tech Company"
                        },
                        new
                        {
                            Id = new Guid("ddc380f3-7ae8-4766-b147-aba16bc259da"),
                            Capacity = 5,
                            Name = "Lviv School"
                        },
                        new
                        {
                            Id = new Guid("208fb852-49a2-4e83-a380-cd0c364fbd65"),
                            Capacity = 5,
                            Name = "City Hospital"
                        });
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Job", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("CitySimulation.Domain.Entities.Person", b =>
                {
                    b.HasOne("CitySimulation.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CitySimulation.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.Navigation("City");

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
